### ISSUE TITLE
Arrow keys don't work with getLine

### ISSUE THREAD

**Issue by michaelmesser** [yamadapc/stack-run#9]
Arrow keys don't work with getLine

```haskell
module Main where

main :: IO ()
main = do
    putStrLn "Enter your name:"
    name <- getLine
    putStrLn $ "Hi " ++ name
```

```
stack run
$ stack build
stack build took 299ms
$ stack exec haskell-test --
Enter your name:
^[[C^[[C^[[C^[[D^[[D^[[D

```

**Comment by yamadapc** [comment]
This would behave the same with or without `stack-run`. To handle cursor movement you need a `readline` wrapper or something to parse the sequences.

There's https://hackage.haskell.org/package/haskeline as `readline`.

Internally `stack-run` uses parsing from `vty`, which you can see here: https://github.com/yamadapc/stack-run/blob/master/unix/System/Console/Questioner.hs#L115-L164.

Closing as invalid/not related.
